format = "$directory$git_branch$git_status$cmd_duration$line_break$character"

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 4

[git_branch]
symbol = " "

[git_status]
ahead = "⇡$count"
behind = "⇣$count"
